// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sx3ERcdAG6itf9PoNvoQTY
import * as React from "react";
import { EmbedCss } from "@plasmicpkgs/plasmic-embed-css"; // plasmic-import: qF0uJxFztB/codeComponent

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  embedCssProps?: Partial<
    Omit<React.ComponentProps<typeof EmbedCss>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, embedCssProps } = props;

  return (
    <EmbedCss
      {...embedCssProps}
      css={
        embedCssProps && "css" in embedCssProps
          ? embedCssProps.css!
          : ("html{\r\n    scroll-behavior: smooth !important;\r\n}\r\n\r\n.splash-bg-anim-class {\r\n    background: linear-gradient(319deg, #3c3c3c, #232322, #686866, #000000, #3c3c3c);\r\n    background-size: 1000% 1000%;\r\n\r\n    -webkit-animation: splash-bg-anim 33s ease infinite;\r\n    -moz-animation: splash-bg-anim 33s ease infinite;\r\n    animation: splash-bg-anim 33s ease infinite;\r\n}\r\n\r\n@-webkit-keyframes splash-bg-anim {\r\n    0%{background-position:0% 88%}\r\n    50%{background-position:100% 13%}\r\n    100%{background-position:0% 88%}\r\n}\r\n@-moz-keyframes splash-bg-anim {\r\n    0%{background-position:0% 88%}\r\n    50%{background-position:100% 13%}\r\n    100%{background-position:0% 88%}\r\n}\r\n@keyframes splash-bg-anim {\r\n    0%{background-position:0% 88%}\r\n    50%{background-position:100% 13%}\r\n    100%{background-position:0% 88%}\r\n}" as const)
      }
    >
      {children}
    </EmbedCss>
  );
}
