// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sx3ERcdAG6itf9PoNvoQTY
// Component: nVIO1bPvnki
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import SectionHeading from "../../SectionHeading"; // plasmic-import: 9cHukr1vk4/component

import { useScreenVariants as useScreenVariantsjp7EaCu1Pi8YJ } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: Jp7eaCu1Pi8yJ/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_the_boss_web_s.module.css"; // plasmic-import: sx3ERcdAG6itf9PoNvoQTY/projectcss
import sty from "./PlasmicGuestTestimonial5.module.css"; // plasmic-import: nVIO1bPvnki/css

export type PlasmicGuestTestimonial5__VariantMembers = {};

export type PlasmicGuestTestimonial5__VariantsArgs = {};
type VariantPropType = keyof PlasmicGuestTestimonial5__VariantsArgs;
export const PlasmicGuestTestimonial5__VariantProps =
  new Array<VariantPropType>();

export type PlasmicGuestTestimonial5__ArgsType = {};
type ArgPropType = keyof PlasmicGuestTestimonial5__ArgsType;
export const PlasmicGuestTestimonial5__ArgProps = new Array<ArgPropType>();

export type PlasmicGuestTestimonial5__OverridesType = {
  root?: p.Flex<"div">;
  sectionHeading?: p.Flex<typeof SectionHeading>;
  testimonial3?: p.Flex<"div">;
  frame74?: p.Flex<"div">;
  frame310?: p.Flex<"div">;
  image12?: p.Flex<"div">;
  loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn3?: p.Flex<"div">;
  frame75?: p.Flex<"div">;
  rectangle43?: p.Flex<"div">;
  frame76?: p.Flex<"div">;
  testimonial?: p.Flex<"div">;
  frame70?: p.Flex<"div">;
  frame308?: p.Flex<"div">;
  image10?: p.Flex<"div">;
  loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn?: p.Flex<"div">;
  frame69?: p.Flex<"div">;
  rectangle31?: p.Flex<"div">;
  frame68?: p.Flex<"div">;
  testimonial2?: p.Flex<"div">;
  frame71?: p.Flex<"div">;
  frame309?: p.Flex<"div">;
  image11?: p.Flex<"div">;
  loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn2?: p.Flex<"div">;
  frame72?: p.Flex<"div">;
  rectangle32?: p.Flex<"div">;
  frame73?: p.Flex<"div">;
};

export interface DefaultGuestTestimonial5Props {
  className?: string;
}

function PlasmicGuestTestimonial5__RenderFunc(props: {
  variants: PlasmicGuestTestimonial5__VariantsArgs;
  args: PlasmicGuestTestimonial5__ArgsType;
  overrides: PlasmicGuestTestimonial5__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjp7EaCu1Pi8YJ()
  });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <SectionHeading
        data-plasmic-name={"sectionHeading"}
        data-plasmic-override={overrides.sectionHeading}
        className={classNames("__wab_instance", sty.sectionHeading)}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__trrFp
          )}
        >
          {"Hall Of Appreciations"}
        </div>
      </SectionHeading>

      {true ? (
        <div className={classNames(projectcss.all, sty.freeBox__mG6Bo)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__f0NsJ
            )}
          >
            {"We are grateful to all our guests"}
          </div>
        </div>
      ) : null}
      {true ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox___245E8)}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"testimonial3"}
            data-plasmic-override={overrides.testimonial3}
            hasGap={true}
            className={classNames(projectcss.all, sty.testimonial3)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"frame74"}
              data-plasmic-override={overrides.frame74}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame74)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"frame310"}
                data-plasmic-override={overrides.frame310}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame310)}
              >
                <div
                  data-plasmic-name={"image12"}
                  data-plasmic-override={overrides.image12}
                  className={classNames(projectcss.all, sty.image12)}
                />
              </p.Stack>

              <div
                data-plasmic-name={
                  "loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn3"
                }
                data-plasmic-override={
                  overrides.loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn3
                }
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn3
                )}
              >
                {
                  "Happy to have interacted on the slice-of-life spirited talk-cast of Sarthak Varshney! Thanks a ton for bearing with my two cents and idiosyncrasies bud...It's a good feeling to catch a breath and look back at the journey and exuberance; my journey of challenging myself, self-prep and doing what I had always loved to do; no grudge with what I had given up for this; not worth at all in comparison to the pride and happiness which I get being Brands Invincible"
                }
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame75"}
              data-plasmic-override={overrides.frame75}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame75)}
            >
              <div
                data-plasmic-name={"rectangle43"}
                data-plasmic-override={overrides.rectangle43}
                className={classNames(projectcss.all, sty.rectangle43)}
              />

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame76"}
                data-plasmic-override={overrides.frame76}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame76)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zAf9J
                  )}
                >
                  {"Peeush Tomar"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2Qdpd
                  )}
                >
                  {"Founder, Brands Invincible"}
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>

          <p.Stack
            as={"div"}
            data-plasmic-name={"testimonial"}
            data-plasmic-override={overrides.testimonial}
            hasGap={true}
            className={classNames(projectcss.all, sty.testimonial)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"frame70"}
              data-plasmic-override={overrides.frame70}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame70)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"frame308"}
                data-plasmic-override={overrides.frame308}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame308)}
              >
                <div
                  data-plasmic-name={"image10"}
                  data-plasmic-override={overrides.image10}
                  className={classNames(projectcss.all, sty.image10)}
                />
              </p.Stack>

              <div
                data-plasmic-name={
                  "loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn"
                }
                data-plasmic-override={
                  overrides.loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn
                }
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn
                )}
              >
                {
                  "Thank you Sarthak for having me and share my experiences, learnings over time.\nI also extend my heartiest thanks to every single person who played an important role in helping and supporting me over the years. Friends, family, peers and acquaintances."
                }
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame69"}
              data-plasmic-override={overrides.frame69}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame69)}
            >
              <div
                data-plasmic-name={"rectangle31"}
                data-plasmic-override={overrides.rectangle31}
                className={classNames(projectcss.all, sty.rectangle31)}
              />

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame68"}
                data-plasmic-override={overrides.frame68}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame68)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4Nc7P
                  )}
                >
                  {"Amanpreet Singh"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__f1PR
                  )}
                >
                  {"Founder, F13 Technologies"}
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>

          <p.Stack
            as={"div"}
            data-plasmic-name={"testimonial2"}
            data-plasmic-override={overrides.testimonial2}
            hasGap={true}
            className={classNames(projectcss.all, sty.testimonial2)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"frame71"}
              data-plasmic-override={overrides.frame71}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame71)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"frame309"}
                data-plasmic-override={overrides.frame309}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame309)}
              >
                <div
                  data-plasmic-name={"image11"}
                  data-plasmic-override={overrides.image11}
                  className={classNames(projectcss.all, sty.image11)}
                />
              </p.Stack>

              <div
                data-plasmic-name={
                  "loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn2"
                }
                data-plasmic-override={
                  overrides.loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn2
                }
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn2
                )}
              >
                {
                  "So Konark Sharma and I had a fun conversation with Sarthak Varshney about our journey at FreeStand Sampling Solutions.\n\nLaunching India's first Digital Product Sampling Platform for FMCG that fully digitizes and automates product sampling operations for brands."
                }
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame72"}
              data-plasmic-override={overrides.frame72}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame72)}
            >
              <div
                data-plasmic-name={"rectangle32"}
                data-plasmic-override={overrides.rectangle32}
                className={classNames(projectcss.all, sty.rectangle32)}
              />

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame73"}
                data-plasmic-override={overrides.frame73}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame73)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ywfTq
                  )}
                >
                  {"Sneh Soni"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__i9SdL
                  )}
                >
                  {"Founder, Grace n Swagg"}
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>
        </p.Stack>
      ) : null}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "sectionHeading",
    "testimonial3",
    "frame74",
    "frame310",
    "image12",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn3",
    "frame75",
    "rectangle43",
    "frame76",
    "testimonial",
    "frame70",
    "frame308",
    "image10",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn",
    "frame69",
    "rectangle31",
    "frame68",
    "testimonial2",
    "frame71",
    "frame309",
    "image11",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn2",
    "frame72",
    "rectangle32",
    "frame73"
  ],
  sectionHeading: ["sectionHeading"],
  testimonial3: [
    "testimonial3",
    "frame74",
    "frame310",
    "image12",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn3",
    "frame75",
    "rectangle43",
    "frame76"
  ],
  frame74: [
    "frame74",
    "frame310",
    "image12",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn3"
  ],
  frame310: ["frame310", "image12"],
  image12: ["image12"],
  loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn3:
    [
      "loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn3"
    ],
  frame75: ["frame75", "rectangle43", "frame76"],
  rectangle43: ["rectangle43"],
  frame76: ["frame76"],
  testimonial: [
    "testimonial",
    "frame70",
    "frame308",
    "image10",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn",
    "frame69",
    "rectangle31",
    "frame68"
  ],
  frame70: [
    "frame70",
    "frame308",
    "image10",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn"
  ],
  frame308: ["frame308", "image10"],
  image10: ["image10"],
  loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn:
    [
      "loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn"
    ],
  frame69: ["frame69", "rectangle31", "frame68"],
  rectangle31: ["rectangle31"],
  frame68: ["frame68"],
  testimonial2: [
    "testimonial2",
    "frame71",
    "frame309",
    "image11",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn2",
    "frame72",
    "rectangle32",
    "frame73"
  ],
  frame71: [
    "frame71",
    "frame309",
    "image11",
    "loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn2"
  ],
  frame309: ["frame309", "image11"],
  image11: ["image11"],
  loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn2:
    [
      "loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn2"
    ],
  frame72: ["frame72", "rectangle32", "frame73"],
  rectangle32: ["rectangle32"],
  frame73: ["frame73"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  sectionHeading: typeof SectionHeading;
  testimonial3: "div";
  frame74: "div";
  frame310: "div";
  image12: "div";
  loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn3: "div";
  frame75: "div";
  rectangle43: "div";
  frame76: "div";
  testimonial: "div";
  frame70: "div";
  frame308: "div";
  image10: "div";
  loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn: "div";
  frame69: "div";
  rectangle31: "div";
  frame68: "div";
  testimonial2: "div";
  frame71: "div";
  frame309: "div";
  image11: "div";
  loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn2: "div";
  frame72: "div";
  rectangle32: "div";
  frame73: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicGuestTestimonial5__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicGuestTestimonial5__VariantsArgs;
    args?: PlasmicGuestTestimonial5__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicGuestTestimonial5__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicGuestTestimonial5__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicGuestTestimonial5__ArgProps,
          internalVariantPropNames: PlasmicGuestTestimonial5__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicGuestTestimonial5__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGuestTestimonial5";
  } else {
    func.displayName = `PlasmicGuestTestimonial5.${nodeName}`;
  }
  return func;
}

export const PlasmicGuestTestimonial5 = Object.assign(
  // Top-level PlasmicGuestTestimonial5 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sectionHeading: makeNodeComponent("sectionHeading"),
    testimonial3: makeNodeComponent("testimonial3"),
    frame74: makeNodeComponent("frame74"),
    frame310: makeNodeComponent("frame310"),
    image12: makeNodeComponent("image12"),
    loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn3:
      makeNodeComponent(
        "loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn3"
      ),
    frame75: makeNodeComponent("frame75"),
    rectangle43: makeNodeComponent("rectangle43"),
    frame76: makeNodeComponent("frame76"),
    testimonial: makeNodeComponent("testimonial"),
    frame70: makeNodeComponent("frame70"),
    frame308: makeNodeComponent("frame308"),
    image10: makeNodeComponent("image10"),
    loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn:
      makeNodeComponent(
        "loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn"
      ),
    frame69: makeNodeComponent("frame69"),
    rectangle31: makeNodeComponent("rectangle31"),
    frame68: makeNodeComponent("frame68"),
    testimonial2: makeNodeComponent("testimonial2"),
    frame71: makeNodeComponent("frame71"),
    frame309: makeNodeComponent("frame309"),
    image11: makeNodeComponent("image11"),
    loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn2:
      makeNodeComponent(
        "loremIpsumDolorSitAmetConsecteturAdipiscingElitEratCondimentumLectusCrasMassaEtAmetDignissimInVulputateConsequatEstSitNonLaoreetSapienUtMattisNuncCursusAtPellentesqueEgetDiamMaecenasElitMiIn2"
      ),
    frame72: makeNodeComponent("frame72"),
    rectangle32: makeNodeComponent("rectangle32"),
    frame73: makeNodeComponent("frame73"),

    // Metadata about props expected for PlasmicGuestTestimonial5
    internalVariantProps: PlasmicGuestTestimonial5__VariantProps,
    internalArgProps: PlasmicGuestTestimonial5__ArgProps
  }
);

export default PlasmicGuestTestimonial5;
/* prettier-ignore-end */
